// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"database/sql"
)

type Category struct {
	ID           int64
	CategoryName sql.NullString
	CreatedAt    sql.NullTime
}

type Post struct {
	ID        int64
	Title     string
	Content   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Deleted   int16
	PubDate   sql.NullTime
	CoverImg  sql.NullString
}

type PostCategory struct {
	PostID     int64
	CategoryID int64
}

type PostTag struct {
	PostID int64
	TagID  int64
}

type Tag struct {
	ID        int64
	TagName   sql.NullString
	CreatedAt sql.NullTime
}

type User struct {
	ID        int64
	Username  string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Deleted   int16
}
